# Generated by Django 5.0.2 on 2024-03-07 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoHome', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'новость', 'verbose_name_plural': 'новости'},
        ),
    ]
